import type {
  PolicyDto,
  PolicyNotificationDto,
  SimulationResult,
  TrendDistrictResult,
  TrendReport,
} from '@dms/shared';

export const district = (overrides: Partial<TrendDistrictResult> = {}): TrendDistrictResult => ({
  districtId: 1,
  name: 'Kegalle',
  province: 'Sabaragamuwa',
  latitude: 7.25,
  longitude: 80.35,
  verifiedCount: 8,
  historicalCount: 2,
  riskLevel: 'High',
  rainfallMm: 120.5,
  maxRiverLevelM: 3.4,
  ...overrides,
});

export const trendReport = (overrides: Partial<TrendReport> = {}): TrendReport => ({
  id: 5,
  hazardType: 'Flood',
  periodStart: '2026-07-01',
  periodEnd: '2026-09-30',
  thresholds: { riskThreshold: 5, mediumRatio: 0.5, minDataPoints: 3 },
  sparse: false,
  hydrometAvailable: true,
  summary: {
    totalVerified: 12,
    totalHistorical: 3,
    highRiskCount: 1,
    trendDirection: 'Rising',
    percentChange: 25,
  },
  districts: [
    district(),
    district({
      districtId: 2,
      name: 'Ratnapura',
      province: 'Sabaragamuwa',
      verifiedCount: 3,
      historicalCount: 0,
      riskLevel: 'Medium',
      rainfallMm: null,
      maxRiverLevelM: null,
    }),
    district({
      districtId: 3,
      name: 'Galle',
      province: 'Southern',
      verifiedCount: 0,
      historicalCount: 0,
      riskLevel: 'Low',
      rainfallMm: null,
      maxRiverLevelM: null,
    }),
  ],
  monthly: [
    { month: '2026-07', verified: 2, historical: 1 },
    { month: '2026-08', verified: 4, historical: 1 },
    { month: '2026-09', verified: 6, historical: 1 },
  ],
  createdAt: '2026-10-01T08:00:00.000Z',
  ...overrides,
});

export const policy = (overrides: Partial<PolicyDto> = {}): PolicyDto => ({
  id: 11,
  policyKey: 'P-2026-001',
  version: 1,
  status: 'Draft',
  title: 'National Flood Mitigation Act',
  description: 'Reduce flood losses.',
  hazardType: 'Flood',
  trendReportId: 5,
  districtIds: [1, 2],
  regionLabel: 'Kegalle, Ratnapura',
  mitigationStrategies: 'Deploy early alerts.',
  landUseGuidelines: '',
  resourceRules: '',
  warningRiskThreshold: null,
  proposedEffectiveDate: null,
  authorId: 1,
  authorName: 'Dulaj Serasinghe',
  effectiveDate: null,
  supersededBy: null,
  review: null,
  simulationReference: null,
  createdAt: '2026-10-02T08:00:00.000Z',
  updatedAt: '2026-10-02T09:00:00.000Z',
  submittedAt: null,
  ...overrides,
});

export const notification = (
  overrides: Partial<PolicyNotificationDto> = {},
): PolicyNotificationDto => ({
  id: 1,
  recipientName: 'Nimali Perera',
  recipientRole: 'PolicyDirector',
  subject: 'Policy awaiting approval',
  deliveryStatus: 'Sent',
  retryCount: 0,
  ...overrides,
});

export const simulation = (overrides: Partial<SimulationResult> = {}): SimulationResult => ({
  id: 1,
  policyId: 11,
  reference: 'S-2026-0001',
  status: 'Success',
  hazardType: 'Flood',
  input: { intensity: 5, teamsDeployed: 10, sheltersActivated: 10 },
  totals: {
    exposedPopulation: 10000,
    affectedAreaKm2: 100,
    evacuationHours: 6.7,
    shelterCoverage: 0.4,
    waterLitres: 450000,
    foodKg: 18000,
    medicineKits: 500,
  },
  districts: [
    {
      districtId: 1,
      name: 'Kegalle',
      riskLevel: 'High',
      latitude: 7.25,
      longitude: 80.35,
      affectedAreaKm2: 60,
      exposedPopulation: 6000,
      evacuationHours: 4,
      radiusKm: 4.4,
    },
    {
      districtId: 2,
      name: 'Ratnapura',
      riskLevel: 'Medium',
      latitude: 6.68,
      longitude: 80.4,
      affectedAreaKm2: 40,
      exposedPopulation: 4000,
      evacuationHours: 2.7,
      radiusKm: 3.6,
    },
  ],
  createdAt: '2026-10-02T09:30:00.000Z',
  ...overrides,
});
